on: push

jobs: 
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - run: node -v
            - run: git -v
            - run: npm -v
            - run: whoami
            - run: pwd
